### ISSUE TITLE
Add ability to 'cache' (commit) test steps into the test image.

### ISSUE THREAD

**Issue by airstandley** [gtmanfred/teststack#10]
It would be helpful to be able to commit changes made by test setup steps into the test image.
The main target here is installing testing requirements. This step can take a while and is something that generally only needs to be done once for a given test image. Having the ability to commit a  step to the test image instead of running it on every `teststack run` command would be a nice small quality of life improvement.

**Comment by airstandley** [comment]
(Worth noting that it seems like this would currently be much more work than it is worth, especially given you can work around the re-installs by using a shell in the test image)

**Comment by gtmanfred** [comment]
You can also specify just running the test step. Instead of running all of them.

But you have to run it a full time once.

**Comment by airstandley** [comment]
I didn't realize you could specify specific test steps to run. Neat!
