### ISSUE TITLE
Improve handling of build stream parsing

### ISSUE THREAD

**Issue by airstandley** [gtmanfred/teststack#14]
Ran into a case where the [build output echo](https://github.com/gtmanfred/teststack/blob/master/src/teststack/containers/docker.py#L120-L125) crashes, preventing the docker image from building with a json decode error.

>json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 11 (char 10)

Looking over the [docker python client implementation](https://github.com/docker/docker-py/blob/e901eac7a8c5f29c7720eafb9f58c8356cca2324/docker/utils/json_stream.py#L36-L75) it seems like this may be because chunks are not guaranteed to contain the full json object and this particular build has long lines.

**Comment by airstandley** [comment]
It seems like it would be easier to simply use the docker client api's decoding by passing `decode=True`. I'm going to test this out.

**Comment by airstandley** [comment]
Yup `decode` seem to work great. https://github.com/gtmanfred/teststack/pull/15

**Comment by gtmanfred** [comment]
Fixed in #15
